preset: preset2
base:
  background: 'rgba(250, 247, 247, 0.75)'
  text-color: '#204fc7'
accent:
  color-1: '#f09f27'
  color-2: '#f09f27'
font:
  family-default: 'Raleway, Helvetica, Tahoma, Geneva, Arial, sans-serif'
  family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
link:
  regular: 'rgba(7, 31, 214, 0.91)'
  hover: '#f5f3ed'
navigation:
  background: '#f09f27'
  text-color: 'rgba(252, 252, 252, 0.97)'
header:
  background: '#faf7f7'
  background-image: ''
  background-overlay: enabled
  text-color: '#230aa3'
intro:
  background: '#165ff2'
features:
  background: '#ffffff'
  text-color: ''
utility:
  background: '#0d4ae3'
  text-color: '#ffffff'
above:
  background: '#175ce8'
testimonials:
  background: '#b34b4b'
expanded:
  background: '#ffffff'
  text-color: '#2350c2'
footer:
  background: '#f09f27'
offcanvas:
  background: '#4bb5b1'
  text-color: '#eceeef'
  toggle-color: '#b34b4b'
  toggle-visibility: '1'
